# Generated by Django 5.1.1 on 2025-05-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_answersource_project_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturl',
            name='is_included_in_rag',
            field=models.BooleanField(default=True, help_text="Se attivo, l'URL sarà incluso nelle ricerche RAG"),
        ),
    ]
