# Generated by Django 5.1.1 on 2025-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_usersubscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
