# Generated by Django 5.1.1 on 2025-03-30 23:08

from django.db import migrations

def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Profile = apps.get_model('profiles', 'Profile')
    ProfileType = apps.get_model('profiles', 'Profile_type')
    
    # Crea il tipo di profilo predefinito se non esiste
    default_type, _ = ProfileType.objects.get_or_create(type="NORMAL_USER")
    
    # Crea profili per tutti gli utenti che non ne hanno uno
    for user in User.objects.all():
        if not Profile.objects.filter(user=user).exists():
            Profile.objects.create(
                user=user,
                email=user.email,
                profile_type=default_type
            )

class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_agreement_terms'),
    ]

    operations = [
        migrations.RunPython(create_profiles_for_existing_users),
    ]
