# Generated by Django 5.1.1 on 2025-05-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_projecturl_is_included_in_rag'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='allowed_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='chat_bot_api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_public_chat_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecturl',
            name='is_included_in_rag',
            field=models.BooleanField(default=True),
        ),
    ]
