# Generated by Django 5.1.1 on 2025-06-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_project_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
