# Generated by Django 5.1.1 on 2025-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_project_allowed_domains_project_chat_bot_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chatwoot_bot_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='chatwoot_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='chatwoot_inbox_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='chatwoot_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
