# Generated by Django 5.1.1 on 2025-06-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_projectfile_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='chatwoot_bot_id',
        ),
    ]
