# Generated by Django 5.1.1 on 2025-05-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_project_chatwoot_bot_id_project_chatwoot_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chatwoot_website_token',
            field=models.CharField(blank=True, help_text='Token del website Chatwoot', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='chatwoot_widget_code',
            field=models.TextField(blank=True, help_text='Codice JavaScript del widget Chatwoot', null=True),
        ),
    ]
