# Generated by Django 5.1.1 on 2025-05-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_project_chatwoot_website_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chatbot_language',
            field=models.CharField(choices=[('it', 'Italiano'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], default='it', help_text="Lingua dell'interfaccia del chatbot", max_length=10),
        ),
    ]
