# Generated by Django 5.1.1 on 2025-06-13 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_answersource_chunk_index_alter_answersource_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerFilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome del set di filtri', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrizione del set di filtri')),
                ('social_domains', models.JSONField(default=list, help_text='Lista di domini social network da evitare (es: facebook.com, twitter.com)')),
                ('analytics_domains', models.JSONField(default=list, help_text='Lista di domini analytics da evitare (es: google-analytics.com)')),
                ('ads_domains', models.JSONField(default=list, help_text='Lista di domini pubblicitari da evitare')),
                ('privacy_domains', models.JSONField(default=list, help_text='Lista di domini privacy/compliance da evitare (es: iubenda.com)')),
                ('external_services', models.JSONField(default=list, help_text='Lista di altri servizi esterni da evitare')),
                ('url_patterns', models.JSONField(default=list, help_text='Lista di pattern regex per URL da evitare')),
                ('avoid_keywords', models.JSONField(default=list, help_text='Lista di parole chiave nei path da evitare')),
                ('is_default', models.BooleanField(default=False, help_text='Se questo è il set di filtri predefinito')),
                ('is_active', models.BooleanField(default=True, help_text='Se questo set di filtri è attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impostazioni Filtri Crawler',
                'verbose_name_plural': 'Impostazioni Filtri Crawler',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CrawlerExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.CharField(help_text='URL di partenza del crawling', max_length=500)),
                ('status', models.CharField(choices=[('running', 'In esecuzione'), ('completed', 'Completato'), ('failed', 'Fallito'), ('cancelled', 'Annullato')], default='running', max_length=20)),
                ('pages_processed', models.IntegerField(default=0)),
                ('pages_failed', models.IntegerField(default=0)),
                ('urls_found', models.IntegerField(default=0)),
                ('urls_saved', models.IntegerField(default=0)),
                ('crawler_config', models.JSONField(default=dict, help_text='Configurazione utilizzata per questo crawling')),
                ('execution_time', models.FloatField(blank=True, help_text='Tempo di esecuzione in secondi', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Messaggio di errore se fallito')),
                ('visited_urls', models.JSONField(default=list, help_text='Lista degli URL visitati')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_logs', to='profiles.project')),
            ],
            options={
                'verbose_name': 'Log Esecuzione Crawler',
                'verbose_name_plural': 'Log Esecuzioni Crawler',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCrawlerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_depth', models.IntegerField(default=2, help_text='Profondità massima di crawling')),
                ('max_pages', models.IntegerField(default=10, help_text='Numero massimo di pagine da analizzare')),
                ('min_text_length', models.IntegerField(default=500, help_text='Lunghezza minima del testo')),
                ('timeout', models.IntegerField(default=60000, help_text='Timeout in millisecondi')),
                ('enhanced_js_support', models.BooleanField(default=True, help_text='Supporto JavaScript avanzato')),
                ('custom_exclude_patterns', models.JSONField(blank=True, default=list, help_text='Pattern regex aggiuntivi da escludere specifici per questo progetto')),
                ('custom_include_patterns', models.JSONField(blank=True, default=list, help_text='Pattern regex da includere specifici per questo progetto')),
                ('use_llm_extraction', models.BooleanField(default=False, help_text='Usa LLM per estrazione informazioni')),
                ('llm_provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google')], help_text='Provider LLM per estrazione informazioni', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filter_settings', models.ForeignKey(blank=True, help_text='Set di filtri da utilizzare (se vuoto, usa quello predefinito)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.crawlerfiltersettings')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_config', to='profiles.project')),
            ],
            options={
                'verbose_name': 'Configurazione Crawler Progetto',
                'verbose_name_plural': 'Configurazioni Crawler Progetto',
            },
        ),
    ]
