# Generated by Django 5.1.1 on 2025-04-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_projectnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectnote',
            name='last_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
