# Generated by Django 5.1.1 on 2025-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_projectfile_last_indexed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexstatus',
            name='notes_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
