# Generated by Django 5.1.1 on 2025-06-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_crawlerfiltersettings_crawlerexecutionlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcrawlerconfig',
            name='filter_settings',
        ),
        migrations.RemoveField(
            model_name='projectcrawlerconfig',
            name='project',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='is_included_in_rag',
            field=models.BooleanField(default=True, help_text='Se True, il documento è incluso nella ricerca RAG'),
        ),
        migrations.DeleteModel(
            name='CrawlerExecutionLog',
        ),
        migrations.DeleteModel(
            name='CrawlerFilterSettings',
        ),
        migrations.DeleteModel(
            name='ProjectCrawlerConfig',
        ),
    ]
