# Generated by Django 5.1.1 on 2025-06-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_projectcrawlerconfig_filter_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='chatwoot_bot_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
