# Generated by Django 5.1.1 on 2025-06-29 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_project_chatwoot_bot_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconversation',
            name='chatbot_source',
            field=models.CharField(choices=[('own', 'Chatbot Nativo'), ('chatwoot', 'Chatwoot'), ('api', 'API Diretta'), ('internal', 'Interfaccia Interna')], default='internal', help_text='Fonte della conversazione', max_length=10),
        ),
        migrations.AddField(
            model_name='projectconversation',
            name='session_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Dati sessione chatbot'),
        ),
        migrations.CreateModel(
            name='ChatwootChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Integrazione Chatwoot attiva')),
                ('inbox_id', models.CharField(blank=True, help_text='ID Inbox Chatwoot', max_length=50, null=True)),
                ('bot_id', models.CharField(blank=True, help_text='ID Bot Chatwoot', max_length=50, null=True)),
                ('website_token', models.CharField(blank=True, help_text='Token website Chatwoot', max_length=255, null=True)),
                ('widget_code', models.TextField(blank=True, help_text='Codice widget Chatwoot', null=True)),
                ('language', models.CharField(choices=[('it', 'Italiano'), ('en', 'English'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch')], default='it', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Dati aggiuntivi Chatwoot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chatwoot_chatbot', to='profiles.project')),
            ],
            options={
                'verbose_name': 'Chatbot Chatwoot',
                'verbose_name_plural': 'Chatbot Chatwoot',
            },
        ),
        migrations.CreateModel(
            name='OwnChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1f93ff', help_text='Colore principale del widget (hex)', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='#6c757d', max_length=7)),
                ('chat_width', models.PositiveIntegerField(default=350, help_text='Larghezza widget in px')),
                ('chat_height', models.PositiveIntegerField(default=500, help_text='Altezza widget in px')),
                ('position', models.CharField(choices=[('bottom-right', 'Basso Destra'), ('bottom-left', 'Basso Sinistra'), ('top-right', 'Alto Destra'), ('top-left', 'Alto Sinistra')], default='bottom-right', max_length=15)),
                ('auto_open', models.BooleanField(default=False, help_text='Apertura automatica del widget')),
                ('open_delay', models.PositiveIntegerField(default=3, help_text='Ritardo apertura in secondi')),
                ('enable_sounds', models.BooleanField(default=True, help_text='Abilita suoni notifiche')),
                ('show_branding', models.BooleanField(default=False, help_text='Mostra logo/branding della piattaforma')),
                ('title', models.CharField(blank=True, help_text='Titolo del widget', max_length=100)),
                ('welcome_message', models.CharField(default='Ciao! Come posso aiutarti oggi?', max_length=200)),
                ('placeholder_text', models.CharField(default='Scrivi un messaggio...', max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Widget attivo/disattivo')),
                ('allowed_domains', models.JSONField(blank=True, default=list, help_text="Domini autorizzati per l'embed")),
                ('jwt_secret', models.CharField(blank=True, help_text='Chiave segreta per JWT', max_length=255)),
                ('widget_token', models.CharField(blank=True, help_text='Token pubblico del widget', max_length=64, unique=True)),
                ('embed_code_generated_at', models.DateTimeField(blank=True, null=True)),
                ('total_interactions', models.PositiveIntegerField(default=0)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='own_chatbot', to='profiles.project')),
            ],
            options={
                'verbose_name': 'Chatbot Nativo',
                'verbose_name_plural': 'Chatbot Nativi',
            },
        ),
    ]
