# Generated by Django 5.1.1 on 2025-04-18 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_ragdefaultsettings_ragtemplatetype_ragconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEngineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_mode', models.CharField(choices=[('platform', 'Usa credito piattaforma'), ('personal', 'Usa chiavi API personali')], default='platform', max_length=20)),
                ('openai_api_key', models.TextField(blank=True, null=True)),
                ('claude_api_key', models.TextField(blank=True, null=True)),
                ('deepseek_api_key', models.TextField(blank=True, null=True)),
                ('gpt_max_tokens', models.IntegerField(default=4096)),
                ('gpt_timeout', models.IntegerField(default=60)),
                ('gpt_model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4o', max_length=50)),
                ('claude_max_tokens', models.IntegerField(default=4096)),
                ('claude_timeout', models.IntegerField(default=90)),
                ('claude_model', models.CharField(choices=[('claude-3-7-sonnet', 'Claude 3.7 Sonnet'), ('claude-3-opus', 'Claude 3 Opus'), ('claude-3-haiku', 'Claude 3 Haiku')], default='claude-3-7-sonnet', max_length=50)),
                ('deepseek_max_tokens', models.IntegerField(default=2048)),
                ('deepseek_timeout', models.IntegerField(default=30)),
                ('deepseek_model', models.CharField(choices=[('deepseek-coder', 'DeepSeek Coder'), ('deepseek-chat', 'DeepSeek Chat'), ('deepseek-lite', 'DeepSeek Lite')], default='deepseek-coder', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_engine_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
