# Generated by Django 5.1.1 on 2025-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_aienginesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalEmbeddingCache',
            fields=[
                ('file_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('embedding_path', models.CharField(max_length=500)),
                ('chunk_size', models.IntegerField(default=500)),
                ('chunk_overlap', models.IntegerField(default=50)),
                ('embedding_model', models.CharField(default='OpenAIEmbeddings', max_length=50)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('file_size', models.BigIntegerField()),
                ('usage_count', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['file_hash'], name='profiles_gl_file_ha_af2912_idx')],
            },
        ),
    ]
