# profiles/migrations/0012_enable_ownchatbot_by_default.py
# Generated by Django

from django.db import migrations
import uuid


def enable_ownchatbot_for_existing_projects(apps, schema_editor):
	"""
    Abilita OwnChatbot per tutti i progetti esistenti che non ce l'hanno.
    """
	Project = apps.get_model('profiles', 'Project')
	OwnChatbot = apps.get_model('profiles', 'OwnChatbot')

	for project in Project.objects.all():
		try:
			# Controlla se esiste già
			own_chatbot = OwnChatbot.objects.filter(project=project).first()

			if not own_chatbot:
				# Crea nuovo con widget_token unico
				own_chatbot = OwnChatbot.objects.create(
					project=project,
					is_enabled=True,
					title=f'Assistente AI - {project.name}',
					welcome_message='Ciao! Come posso aiutarti oggi?',
					placeholder_text='Scrivi un messaggio...',
					widget_token=str(uuid.uuid4()).replace('-', '')[:32],  # Token unico
					jwt_secret=str(uuid.uuid4())  # Secret unico
				)
				print(f"✅ Creato OwnChatbot per progetto {project.id} - {project.name}")
			else:
				# Se esiste ma è disabilitato, abilitalo
				if not own_chatbot.is_enabled:
					own_chatbot.is_enabled = True
					own_chatbot.save()
					print(f"✅ Abilitato OwnChatbot esistente per progetto {project.id} - {project.name}")

				# Se esiste ma non ha widget_token, generalo
				if not own_chatbot.widget_token:
					own_chatbot.widget_token = str(uuid.uuid4()).replace('-', '')[:32]
					own_chatbot.save()
					print(f"✅ Generato widget_token per OwnChatbot del progetto {project.id}")

				# Se esiste ma non ha jwt_secret, generalo
				if not own_chatbot.jwt_secret:
					own_chatbot.jwt_secret = str(uuid.uuid4())
					own_chatbot.save()
					print(f"✅ Generato jwt_secret per OwnChatbot del progetto {project.id}")

		except Exception as e:
			print(f"❌ Errore per progetto {project.id}: {str(e)}")
			continue


def reverse_migration(apps, schema_editor):
	"""
    Disabilita tutti gli OwnChatbot (per rollback).
    """
	OwnChatbot = apps.get_model('profiles', 'OwnChatbot')
	OwnChatbot.objects.update(is_enabled=False)
	print("✅ Disabilitati tutti gli OwnChatbot")


class Migration(migrations.Migration):
	dependencies = [
		('profiles', '0011_projectconversation_chatbot_source_and_more'),
	]

	operations = [
		migrations.RunPython(enable_ownchatbot_for_existing_projects, reverse_migration),
	]

