# Generated by Django 5.1.1 on 2025-04-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_globalembeddingcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingCacheStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_embeddings', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('total_usage', models.IntegerField(default=0)),
                ('reuse_count', models.IntegerField(default=0)),
                ('estimated_savings', models.FloatField(default=0.0)),
                ('pdf_count', models.IntegerField(default=0)),
                ('docx_count', models.IntegerField(default=0)),
                ('txt_count', models.IntegerField(default=0)),
                ('csv_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('avg_file_size', models.BigIntegerField(default=0)),
                ('max_reuses', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Statistica Cache Embedding',
                'verbose_name_plural': 'Statistiche Cache Embedding',
                'ordering': ['-date'],
            },
        ),
    ]
