# Generated by Django 5.1.1 on 2025-04-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_embeddingcachestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='aienginesettings',
            name='gemini_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aienginesettings',
            name='gemini_max_tokens',
            field=models.IntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='aienginesettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-pro', 'Gemini Pro'), ('gemini-pro-vision', 'Gemini Pro Vision'), ('gemini-ultra', 'Gemini Ultra')], default='gemini-pro', max_length=50),
        ),
        migrations.AddField(
            model_name='aienginesettings',
            name='gemini_timeout',
            field=models.IntegerField(default=45),
        ),
        migrations.AlterField(
            model_name='aienginesettings',
            name='gpt_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-3.5-turbo', max_length=50),
        ),
    ]
