# Generated by Django 5.1.1 on 2025-04-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_aienginesettings_gemini_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aienginesettings',
            name='gemini_max_tokens',
            field=models.IntegerField(default=8192),
        ),
        migrations.AlterField(
            model_name='aienginesettings',
            name='gemini_model',
            field=models.CharField(choices=[('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.0-pro', 'Gemini 1.0 Pro')], default='gemini-1.5-pro', max_length=50),
        ),
        migrations.AlterField(
            model_name='aienginesettings',
            name='gemini_timeout',
            field=models.IntegerField(default=60),
        ),
    ]
