# Generated by Django 5.1.1 on 2025-04-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_alter_aienginesettings_gemini_max_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aienginesettings',
            name='selected_engine',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini')], default='openai', max_length=20),
        ),
    ]
