# Generated by Django 5.1.1 on 2025-04-23 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_aienginesettings_selected_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_engine', models.CharField(choices=[('openai', 'OpenAI'), ('claude', 'Claude'), ('deepseek', 'DeepSeek'), ('gemini', 'Gemini')], default='openai', max_length=20)),
                ('gpt_model', models.CharField(choices=[('gpt-4o', 'GPT-4o'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-4o', max_length=50)),
                ('gpt_max_tokens', models.IntegerField(default=4096)),
                ('gpt_timeout', models.IntegerField(default=60)),
                ('claude_model', models.CharField(choices=[('claude-3-7-sonnet', 'Claude 3.7 Sonnet'), ('claude-3-opus', 'Claude 3 Opus'), ('claude-3-haiku', 'Claude 3 Haiku')], default='claude-3-7-sonnet', max_length=50)),
                ('claude_max_tokens', models.IntegerField(default=4096)),
                ('claude_timeout', models.IntegerField(default=90)),
                ('deepseek_model', models.CharField(choices=[('deepseek-coder', 'DeepSeek Coder'), ('deepseek-chat', 'DeepSeek Chat'), ('deepseek-lite', 'DeepSeek Lite')], default='deepseek-coder', max_length=50)),
                ('deepseek_max_tokens', models.IntegerField(default=2048)),
                ('deepseek_timeout', models.IntegerField(default=30)),
                ('gemini_model', models.CharField(choices=[('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro'), ('gemini-1.0-pro', 'Gemini 1.0 Pro')], default='gemini-1.5-pro', max_length=50)),
                ('gemini_max_tokens', models.IntegerField(default=8192)),
                ('gemini_timeout', models.IntegerField(default=60)),
                ('chunk_size', models.IntegerField(blank=True, null=True)),
                ('chunk_overlap', models.IntegerField(blank=True, null=True)),
                ('similarity_top_k', models.IntegerField(blank=True, null=True)),
                ('mmr_lambda', models.FloatField(blank=True, null=True)),
                ('similarity_threshold', models.FloatField(blank=True, null=True)),
                ('retriever_type', models.CharField(blank=True, max_length=50, null=True)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('auto_citation', models.BooleanField(blank=True, null=True)),
                ('prioritize_filenames', models.BooleanField(blank=True, null=True)),
                ('equal_notes_weight', models.BooleanField(blank=True, null=True)),
                ('strict_context', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='profiles.project')),
                ('rag_preset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_configs', to='profiles.ragdefaultsettings')),
            ],
        ),
    ]
