# Generated by Django 5.1.1 on 2025-04-28 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_defaultsystemprompts_llmprovider_subscriptionplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectllmconfig',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='projectllmconfig',
            name='default_system_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='profiles.defaultsystemprompts'),
        ),
        migrations.AddField(
            model_name='projectllmconfig',
            name='system_prompt_override',
            field=models.TextField(blank=True, help_text='Sovrascrive i prompt predefiniti e personalizzati se specificato'),
        ),
        migrations.AddField(
            model_name='projectllmconfig',
            name='use_custom_prompt',
            field=models.BooleanField(default=False, help_text='Se abilitato, usa il prompt personalizzato anziché quello predefinito'),
        ),
        migrations.CreateModel(
            name='UserCustomPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prompt_text', models.TextField()),
                ('is_public', models.BooleanField(default=False, help_text='Se abilitato, il prompt sarà visibile e utilizzabile da tutti gli utenti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prompt Personalizzato Utente',
                'verbose_name_plural': 'Prompt Personalizzati Utente',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectllmconfig',
            name='custom_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='profiles.usercustomprompt'),
        ),
    ]
