# Generated by Django 5.1.1 on 2025-04-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_projectllmconfig_system_prompt_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectLLMConfig',
            new_name='ProjectLLMConfiguration',
        ),
        migrations.RenameModel(
            old_name='ProjectConfiguration',
            new_name='ProjectRAGConfiguration',
        ),
        migrations.DeleteModel(
            name='IndexStatus',
        ),
    ]
