# Generated by Django 5.1.1 on 2025-05-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_rename_projectllmconfig_projectllmconfiguration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustomprompt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectllmconfiguration',
            name='custom_prompt',
        ),
        migrations.RemoveField(
            model_name='projectllmconfiguration',
            name='system_prompt_override',
        ),
        migrations.AddField(
            model_name='projectllmconfiguration',
            name='custom_prompt_text',
            field=models.TextField(blank=True, help_text='Prompt personalizzato specifico per questo progetto'),
        ),
        migrations.DeleteModel(
            name='RAGConfiguration',
        ),
        migrations.DeleteModel(
            name='UserCustomPrompt',
        ),
    ]
