# Generated by Django 5.1.1 on 2025-05-03 19:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_usercustomprompt_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='notes',
        ),
        migrations.AddField(
            model_name='answersource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answersource',
            name='project_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_answers_from_notes', to='profiles.projectnote'),
        ),
        migrations.DeleteModel(
            name='UserDocument',
        ),
    ]
