# Generated by Django 5.1.1 on 2025-05-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_project_notes_answersource_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
