# Generated by Django 5.1.1 on 2025-05-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_project_metadata_projectfile_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='metadata',
        ),
    ]
