# Generated by Django 5.1.1 on 2025-05-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_remove_projectfile_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectindexstatus',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
