# Generated by Django 5.1.1 on 2025-05-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_projectindexstatus_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
